config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index' #タスク一覧の表示

  resources :boards do #crud機能の作成
    resources:tasks #中に入力すると boardsとtaskが紐づく
  end

  resources :tasks do
    resources :comments, only:[:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#

class Board < ApplicationRecord
    belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task
    belongs_to :user
    validates :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    has_one_attached :eyecatch
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def avatar_image
    'Oval.png'
  end

  has_many :boards, dependent: :destroy #ユーザーがいて記事が紐づいてることを認識させる
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  #  before_action :set_board, only: %i[show]

   def index  #記事一覧を表示するときは[index]をつけるのがルール
     @boards = Board.all
   end

   def show #特定の記事は[show]をつけるのがルール
    @board = Board.find(params[:id])
   end

   def new
    @board = current_user.boards.build
   end

   def create #new
     @board = current_user.boards.build(board_params)
     if @board.save
       redirect_to root_path(@board),notice:'保存しました'
     else
       render :new
     end
   end

   def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board),notice:'更新できました'
    else
      flash.now[:error] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:id])
    board.destroy! #ビックリマークは削除が失敗したときに挙動が止まる
    redirect_to root_path, notice:'削除に成功しました'  #root_pathは記事一覧があるページ
  end

  private
  def board_params
    params.require(:board).permit(:name, :description) #permit = 許可する
  end

  def set_board   #以下を各実行前に処理
    @board = Board.find(params[:id]) #paramsidでボードののId 記事のボードを取得@boardsに代入 @はビューに渡すため
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build
    end

    def create
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        if @comment.save
            redirect_to task_path(task), notice:'コメントを追加'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content).merge(user_id: current_user.id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all #タスクを配列にして挿入
  end

def new
  @task = current_user.tasks.build
end

  def show
    @task = Task.find(params[:id])
    @comments = @task.comments
  end

def create
  @task = current_user.tasks.build(task_params)
     if @task.save
       redirect_to task_path(@task),notice:'保存しました'
     else
       flash.now[:error] = '保存に失敗しました'
       render :new
     end
end

def edit
  @task = Task.find(params[:id]) #viewに渡すために@をつける
end

def update
  @task = Task.find(params[:id])
  if @task.update(task_params) #privateのtask_paramsを持ってくる
    redirect_to task_path(@task), notice:'更新できました'
  else
    flash.now[:error] = '更新できませんでした'
    render :edit
  end
end

def destroy
  task = Task.find(params[:id])
  task.destroy!
  redirect_to root_path, notice:'削除できました'
end

private
def task_params
    params.require(:task).permit(:title, :content, :eyecatch)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
.container
%ul
- board.errors.full_messages.each do |message|
    %li= message    
    = form_with(model:@board, url:board_path(@board),method:'put', local: true) do |f|
    %div
        = f.label :name, 'Name'
    %div
        = f.text_field :name, class: 'text'
    %div
        = f.label :description, 'Description'
    %div
        = f.text_area :description, class:'text'
    %div
        = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
.container
  %p.header_text
  .border_line
  = form_with(model: @board,url: board_path(@board), method: 'put',local: true) do |f| 
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description, class: 'board-text'
    = f.submit 'Submit' ,class: 'btn-primary'

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do|board|
    = link_to board_path(board) do
      .card
        .card_name
          = board.name
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content
              = link_to '編集する',edit_board_path(board)
              = link_to '削除する',board_path(board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか?' }
        .card_description
          = board.description
  .card_add
    = link_to '+ Add new board ', new_board_path 

app/views/boards/new.html.haml
.container
  %p.header_text
  .border_line
  %h2 New Board
  = form_with(model: @board,url: boards_path, method: 'post',local: true) do |f| 
    %div
      = f.label :name, 'タイトル'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, '概要'
    %div
      = f.text_area :description, class: 'board-text'
    = f.submit '保存' ,class: 'btn-primary'

app/views/boards/show.html.haml
=form_with(model:@board, url:board_path, method:'get', local:true) do |f|
  %div
    =f.text_field :name, class: 'text'
  %div
    =f.text_area :description, class: 'text'
  %div
    =f.submit :Submit, class:'btn-primary'

app/views/comments/new.html.haml
= form_with(model:@comment, url: task_comments_path(@comment.task), local:true) do |f|
  %div
    = f.label :content, '内容'
  %div
    = f.text_area :content
  = f.submit '保存', class:'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'Oval.png', class: 'header_back'
        %p.header_pageTitle 
          = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
          
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/edit.html.haml
.container
  %p.header_text
  .border_line
  %h2 New Card
  = form_with(model: @task, url: task_path(@task), method: 'put', local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'board-text'
    = f.submit '保存' ,class: 'btn-primary'

app/views/tasks/index.html.haml
.container
  %h2 Brackets
  - @tasks.each do|task|
    = link_to task_path(task) do
      .content
        - if task.eyecatch.attached?
          = image_tag task.eyecatch, class: 'eyecatch'
        .content-box
          %p.content-left 
            = task.title
        %p.content-writing
          = task.content
  .card_add
    = link_to '+ Add new card ', new_task_path 
      

app/views/tasks/new.html.haml
.container
  %p.header_text
  .border_line
  %h2 New Card
  = form_with(model: @task, url: tasks_path, method: 'post', local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'board-text'
    = f.submit '保存' ,class: 'btn-primary'

app/views/tasks/show.html.haml
.container
  .task-box
    .task-top
      .title 
        = @task.title
      - if user_signed_in? && current_user.tasks.exists?(id: @task.id)
        .image
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtn'
            .dropdown-content
              = link_to  '編集', edit_task_path(@task)
              = link_to '削除', task_path(@task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか?' }
    - if @task.eyecatch.attached?
      = image_tag @task.eyecatch, class: 'eyecatch'
    .content
      .content-box
        %p.content-left 
      %p.content-writing
        = @task.content

.comment
  %h2 コメント一覧
  - @comments.each do |comment|
    .comment-box
      .comment-box-img
        = image_tag 'Oval(1).png', class: 'avater'
      .comment-box-content
        = comment.content

= link_to new_task_comment_path(@task) do
  .btn-secondary
    コメントを追加